#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "tbp.racc".
#

require 'racc/parser'


#
# $Id: tbp.racc 494 2010-05-02 03:39:44Z nicb $
#

require File.dirname(__FILE__) + '/../tape'

require 'yaml'

class DescriptionTapeParseError < StandardError
end


module Tdp

  module Tape

    class BoxParser < Racc::Parser

module_eval <<'..end tbp.racc modeval..id3398be8209', 'tbp.racc', 153

  attr_accessor :line, :yydebug, :tape

  require 'lexer'

  include Tdp::Tape::Lexer

  def initialize(tape, debug = false)
    @line = 1
    @yydebug = debug
    @tape = tape
  end

  def parse(one_line)
    begin
        result = tbp_lexer(one_line, :bump_line, yydebug) { do_parse }
    rescue ParseError
        raise ParseError.new("Box Description failed at line #{line}: #{$!}")
    end
    return result
  end

  def next_token
    @q.shift
  end

  def bump_line(inc = 1)
    self.line += inc
  end

  def dump
    fh = File.open(tape.filename, 'w') do
        |out|
        YAML.dump(tape, out)
    end
  end

..end tbp.racc modeval..id3398be8209

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 3, 35, :_reduce_1,
 5, 36, :_reduce_2,
 4, 36, :_reduce_3,
 2, 36, :_reduce_4,
 2, 36, :_reduce_none,
 3, 36, :_reduce_6,
 1, 36, :_reduce_7,
 3, 39, :_reduce_8,
 4, 38, :_reduce_9,
 4, 38, :_reduce_10,
 7, 41, :_reduce_11,
 4, 41, :_reduce_12,
 1, 42, :_reduce_none,
 3, 44, :_reduce_14,
 1, 46, :_reduce_none,
 2, 46, :_reduce_none,
 3, 45, :_reduce_17,
 2, 45, :_reduce_18,
 1, 45, :_reduce_none,
 1, 47, :_reduce_none,
 1, 47, :_reduce_none,
 3, 43, :_reduce_22,
 2, 43, :_reduce_23,
 1, 43, :_reduce_none,
 1, 48, :_reduce_none,
 1, 48, :_reduce_none,
 1, 48, :_reduce_none,
 1, 48, :_reduce_none,
 2, 40, :_reduce_29,
 1, 40, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 2, 49, :_reduce_36,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 1, 49, :_reduce_none,
 2, 37, :_reduce_47,
 1, 37, :_reduce_none ]

racc_reduce_n = 49

racc_shift_n = 76

racc_action_table = [
    20,    21,    22,    23,    26,    13,    30,    32,    35,    18,
    46,    71,    16,    69,     2,    27,    46,    31,    33,    20,
    21,    22,    23,    26,    48,    30,    32,    41,    18,    34,
    48,    19,    39,     6,    27,    39,    31,    33,    20,    21,
    22,    23,    26,    10,    30,    32,    35,    18,    34,    46,
    19,    52,     6,    27,     6,    31,    33,    38,    13,    50,
    13,    53,    10,    48,    10,    54,    14,    34,     6,    19,
    20,    21,    22,    23,    26,    56,    30,    32,    35,    18,
     6,    38,    65,     5,     4,    27,    72,    31,    33,     3,
    13,    74,    63,   nil,   nil,   nil,   nil,   nil,   nil,    34,
   nil,    19,    20,    21,    22,    23,    26,   nil,    30,    32,
    35,    18,   nil,   nil,   nil,   nil,   nil,    27,   nil,    31,
    33,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    34,   nil,    19,    20,    21,    22,    23,    26,    62,
    30,    32,    35,    18,    58,   nil,   nil,   nil,   nil,    61,
   nil,   nil,    33,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    63,    20,    21,    22,    23,    26,    62,    30,
    32,    35,    18,    58,   nil,   nil,   nil,   nil,    61,   nil,
   nil,    33,    66,    21,    22,    23,    26,    62,    30,    32,
    35,    18,    58,   nil,   nil,   nil,   nil,    61,   nil,    68,
    33 ]

racc_action_check = [
    39,    39,    39,    39,    39,    11,    39,    39,    39,    39,
    41,    65,    11,    65,     0,    39,    52,    39,    39,    29,
    29,    29,    29,    29,    41,    29,    29,    29,    29,    39,
    52,    39,    25,     4,    29,    42,    29,    29,    43,    43,
    43,    43,    43,     4,    43,    43,    43,    43,    29,    44,
    29,    44,     7,    43,    16,    43,    43,    24,    17,    43,
     8,    47,     7,    44,    16,    49,     8,    43,    14,    43,
    15,    15,    15,    15,    15,    54,    15,    15,    15,    15,
    10,    60,    63,     3,     2,    15,    66,    15,    15,     1,
    15,    71,    72,   nil,   nil,   nil,   nil,   nil,   nil,    15,
   nil,    15,    36,    36,    36,    36,    36,   nil,    36,    36,
    36,    36,   nil,   nil,   nil,   nil,   nil,    36,   nil,    36,
    36,   nil,    36,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    36,   nil,    36,    56,    56,    56,    56,    56,    56,
    56,    56,    56,    56,    56,   nil,   nil,   nil,   nil,    56,
   nil,   nil,    56,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    56,    68,    68,    68,    68,    68,    68,    68,
    68,    68,    68,    68,   nil,   nil,   nil,   nil,    68,   nil,
   nil,    68,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    64,    64,   nil,   nil,   nil,   nil,    64,   nil,    64,
    64 ]

racc_action_pointer = [
   -13,    89,    61,    83,    11,   nil,   nil,    30,    38,   nil,
    58,   -17,   nil,   nil,    46,    68,    32,    36,   nil,   nil,
   nil,   nil,   nil,   nil,    37,    13,   nil,   nil,   nil,    17,
   nil,   nil,   nil,   nil,   nil,   nil,   100,   nil,   nil,    -2,
   nil,    -7,    16,    36,    32,   nil,   nil,    38,   nil,    63,
   nil,   nil,    -1,   nil,    56,   nil,   132,   nil,   nil,   nil,
    61,   nil,   nil,    63,   180,   -20,    67,   nil,   161,   nil,
   nil,    87,    62,   nil,   nil,   nil ]

racc_action_default = [
   -49,   -49,   -49,   -49,   -49,    76,   -48,    -1,   -49,    -7,
   -49,    -5,    -4,   -47,   -49,   -49,   -49,    -6,   -41,   -35,
   -38,   -39,   -44,   -42,   -32,    -8,   -40,   -31,   -30,   -49,
   -45,   -33,   -46,   -37,   -34,   -43,   -49,    -3,   -36,   -49,
   -29,   -43,    -2,   -49,   -13,   -19,   -20,   -49,   -21,   -49,
    -9,   -18,   -49,   -10,   -49,   -17,   -49,   -12,   -26,   -24,
   -28,   -25,   -27,   -49,   -49,   -49,   -38,   -23,   -49,   -15,
   -14,   -49,   -49,   -22,   -16,   -11 ]

racc_goto_table = [
    25,    57,    40,     8,    64,    49,    11,    44,     9,    15,
    60,    12,    70,    17,    47,    36,    40,    75,    60,    59,
    37,    42,    60,    45,    43,     7,    51,    67,     1,   nil,
   nil,    73,   nil,   nil,    55 ]

racc_goto_check = [
     4,    10,    16,     3,     9,     8,     3,    11,     5,     3,
    15,     5,    12,     3,     7,     3,    16,    10,    15,    14,
     5,     4,    15,    13,     6,     2,    13,    14,     1,   nil,
   nil,    14,   nil,   nil,    13 ]

racc_goto_pointer = [
   nil,    28,    21,    -1,   -15,     4,   -15,   -27,   -36,   -52,
   -55,   -34,   -53,   -18,   -37,   -46,   -27 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    24,    28 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :COMMA => 2,
 :COLON => 3,
 :RPAR => 4,
 :RSQ => 5,
 :DASH => 6,
 :RBRACE => 7,
 :QUESTION_MARK => 8,
 :EQ => 9,
 :LPAR => 10,
 :LSQ => 11,
 :LBRACE => 12,
 :SESSION_HEADER => 13,
 :DATE => 14,
 :LOCATION => 15,
 :TRANSFERRER => 16,
 :ANYWORD => 17,
 :TAPE_TAG => 18,
 :WHITE_SPACE => 19,
 :PUNCTUATION => 20,
 :ID_TAG => 21,
 :EMPTY_LINE => 22,
 :EOL => 23,
 :TAPE_CONTENT_HEADER => 24,
 :TAPE_SEGMENT => 25,
 :DOLLAR => 26,
 :TAPE_BOX_HEADER => 27,
 :NO_DISPLAYS => 28,
 :DISPLAY_TERM_SEPARATOR => 29,
 :CALLIGRAPHY => 30,
 :QUESTION_MARKS => 31,
 :DISPLAY_LOCATION => 32,
 :AUTHOR_INITIALS => 33 }

racc_use_result_var = true

racc_nt_base = 34

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'COMMA',
'COLON',
'RPAR',
'RSQ',
'DASH',
'RBRACE',
'QUESTION_MARK',
'EQ',
'LPAR',
'LSQ',
'LBRACE',
'SESSION_HEADER',
'DATE',
'LOCATION',
'TRANSFERRER',
'ANYWORD',
'TAPE_TAG',
'WHITE_SPACE',
'PUNCTUATION',
'ID_TAG',
'EMPTY_LINE',
'EOL',
'TAPE_CONTENT_HEADER',
'TAPE_SEGMENT',
'DOLLAR',
'TAPE_BOX_HEADER',
'NO_DISPLAYS',
'DISPLAY_TERM_SEPARATOR',
'CALLIGRAPHY',
'QUESTION_MARKS',
'DISPLAY_LOCATION',
'AUTHOR_INITIALS',
'$start',
'box',
'display',
'empty_lines',
'display_term',
'full_term',
'filled_line',
'calligraphy',
'pen',
'additional_info_words',
'author',
'calligraphy_words',
'author_initials',
'calligraphy_word',
'additional_info_word',
'punctuation',
'word']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'tbp.racc', 24
  def _reduce_1( val, _values, result )
        tape.box = val[2]
        result = tape
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 32
  def _reduce_2( val, _values, result )
            d = val[0].last
            d.notes << val[4]
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 37
  def _reduce_3( val, _values, result )
            val[0] << val[3]
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 42
  def _reduce_4( val, _values, result )
            val[0] << val[1]
            result = val[0]
   result
  end
.,.,

 # reduce 5 omitted

module_eval <<'.,.,', 'tbp.racc', 43
  def _reduce_6( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 48
  def _reduce_7( val, _values, result )
            result = [ val[0] ]
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 56
  def _reduce_8( val, _values, result )
            d = Tdp::Box::Display.new(val[0].sub(/\A(@==@)+\s+\(/,'').sub(/\)@@\Z/,''))
            d.notes << val[2]
            result = d
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 64
  def _reduce_9( val, _values, result )
            n = val[0]
            n.lines = val[1..3].join.sub(/\A /, '')
            result = n
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 71
  def _reduce_10( val, _values, result )
            n = Tdp::Box::Note.new
            n.lines = val[0].sub(/\A /, '')
            n.calligraphy = val[2]
            result = n
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 77
  def _reduce_11( val, _values, result )
            result = Tdp::Tape::CalligraphyDescription.new(val[0], val[6], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 77
  def _reduce_12( val, _values, result )
 result = Tdp::Tape::CalligraphyDescription.new(val[0], val[3])
   result
  end
.,.,

 # reduce 13 omitted

module_eval <<'.,.,', 'tbp.racc', 83
  def _reduce_14( val, _values, result )
 result = val[2]
   result
  end
.,.,

 # reduce 15 omitted

 # reduce 16 omitted

module_eval <<'.,.,', 'tbp.racc', 90
  def _reduce_17( val, _values, result )
 result = val.join
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 91
  def _reduce_18( val, _values, result )
 result = val.join
   result
  end
.,.,

 # reduce 19 omitted

 # reduce 20 omitted

 # reduce 21 omitted

module_eval <<'.,.,', 'tbp.racc', 99
  def _reduce_22( val, _values, result )
 result = val.join
   result
  end
.,.,

module_eval <<'.,.,', 'tbp.racc', 100
  def _reduce_23( val, _values, result )
 result = val.join
   result
  end
.,.,

 # reduce 24 omitted

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

module_eval <<'.,.,', 'tbp.racc', 110
  def _reduce_29( val, _values, result )
 result = val.join
   result
  end
.,.,

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

module_eval <<'.,.,', 'tbp.racc', 121
  def _reduce_36( val, _values, result )
 result = val.join
   result
  end
.,.,

 # reduce 37 omitted

 # reduce 38 omitted

 # reduce 39 omitted

 # reduce 40 omitted

 # reduce 41 omitted

 # reduce 42 omitted

 # reduce 43 omitted

 # reduce 44 omitted

 # reduce 45 omitted

 # reduce 46 omitted

module_eval <<'.,.,', 'tbp.racc', 134
  def _reduce_47( val, _values, result )
 result = val.join
   result
  end
.,.,

 # reduce 48 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class BoxParser

  end   # module Tape

end   # module Tdp

#
# test code - to be commented out in production
#
#
# require '../tape'
# tape = Tdp::Tape::Item.new
# tbp = Tdp::Tape::BoxParser.new(tape, true)
# fh = File.open(ARGV[0], 'r')
# one_line = fh.gets
# tape = tbp.parse(one_line)
# $stderr.puts("tape: #{tape.inspect}")
