#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "tcp.racc".
#

require 'racc/parser'


#
# $Id: tcp.racc 379 2009-04-23 03:45:04Z nicb $
#

require File.dirname(__FILE__) + '/../tape'

require 'yaml'

class DescriptionTapeParseError < StandardError
end


module Tdp

  module Tape

    class ContentParser < Racc::Parser

module_eval <<'..end tcp.racc modeval..id7c0e040f4d', 'tcp.racc', 75

  attr_accessor :line, :yydebug, :tape, :content_buffer

  require 'lexer'

  include Tdp::Tape::Lexer

  def initialize(tape, debug = false)
    @line = 1
    @yydebug = debug
    @tape = tape
    @content_buffer = []
  end

  def parse(one_line)
    begin
        result = tcp_lexer(one_line, :bump_line) { do_parse }
    rescue ParseError
        raise ParseError.new("Content Description failed at line #{line}: #{$!}")
    end
    return result
  end

  def next_token
    @q.shift
  end

  def bump_line(inc = 1)
    self.line += inc
  end

  def dump
    fh = File.open(session.filename, 'w') do
        |out|
        YAML.dump(session, out)
    end
  end

..end tcp.racc modeval..id7c0e040f4d

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 4, 24, :_reduce_1,
 3, 25, :_reduce_none,
 2, 27, :_reduce_none,
 1, 27, :_reduce_none,
 4, 28, :_reduce_5,
 4, 28, :_reduce_6,
 4, 28, :_reduce_7,
 4, 28, :_reduce_8,
 3, 30, :_reduce_9,
 5, 30, :_reduce_10,
 2, 29, :_reduce_11,
 1, 29, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 2, 32, :_reduce_none,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none,
 2, 26, :_reduce_none,
 1, 26, :_reduce_none ]

racc_reduce_n = 26

racc_shift_n = 43

racc_action_table = [
    17,    19,    20,     9,    23,    24,    10,    38,     3,    41,
     6,    18,     6,    21,    22,    29,    17,    19,    20,    27,
    23,    24,    34,    35,    14,    14,    11,    18,    33,    21,
    22,     8,    17,    19,    20,    27,    23,    24,     7,     6,
    39,     4,    10,    18,    42,    21,    22,    10,   nil,    31,
   nil,    27,    17,    19,    20,   nil,    23,    24,   nil,   nil,
   nil,   nil,   nil,    18,   nil,    21,    22,   nil,   nil,    36,
   nil,    27,    17,    19,    20,   nil,    23,    24,   nil,   nil,
   nil,   nil,   nil,    18,   nil,    21,    22,   nil,   nil,   nil,
   nil,    27 ]

racc_action_check = [
    15,    15,    15,     5,    15,    15,     5,    31,     0,    36,
    31,    15,    36,    15,    15,    14,    16,    16,    16,    15,
    16,    16,    29,    29,    12,     9,     7,    16,    28,    16,
    16,     4,    25,    25,    25,    16,    25,    25,     3,     2,
    35,     1,    37,    25,    39,    25,    25,    40,   nil,    25,
   nil,    25,    30,    30,    30,   nil,    30,    30,   nil,   nil,
   nil,   nil,   nil,    30,   nil,    30,    30,   nil,   nil,    30,
   nil,    30,    13,    13,    13,   nil,    13,    13,   nil,   nil,
   nil,   nil,   nil,    13,   nil,    13,    13,   nil,   nil,   nil,
   nil,    13 ]

racc_action_pointer = [
    -7,    41,    21,    18,    31,   -12,   nil,     7,   nil,    17,
   nil,   nil,    16,    70,    -6,    -2,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    30,   nil,   nil,    12,    17,
    50,    -8,   nil,   nil,   nil,    19,    -6,    24,   nil,    39,
    29,   nil,   nil ]

racc_action_default = [
   -26,   -26,   -26,   -26,   -26,   -26,   -25,   -26,    43,   -26,
   -24,    -2,    -1,    -4,   -26,   -26,    -3,   -22,   -13,   -23,
   -20,   -16,   -18,   -21,   -19,   -26,   -12,   -15,   -14,   -26,
   -26,   -26,   -11,   -17,    -9,   -26,   -26,    -6,    -5,   -26,
    -8,    -7,   -10 ]

racc_goto_table = [
     5,    32,    13,    12,     2,    16,    32,    30,     1,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    37,
   nil,   nil,   nil,   nil,    40 ]

racc_goto_check = [
     3,     8,     5,     4,     2,     5,     8,     6,     1,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,
   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     8,     4,    -2,    -6,    -7,    -8,   nil,   -24,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    25,    15,    26,    28 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :COMMA => 2,
 :COLON => 3,
 :RPAR => 4,
 :RSQ => 5,
 :DASH => 6,
 :LPAR => 7,
 :LSQ => 8,
 :SESSION_HEADER => 9,
 :DATE => 10,
 :LOCATION => 11,
 :TRANSFERRER => 12,
 :ANYWORD => 13,
 :TAPE_TAG => 14,
 :WHITE_SPACE => 15,
 :PUNCTUATION => 16,
 :ID_TAG => 17,
 :EMPTY_LINE => 18,
 :EOL => 19,
 :TAPE_CONTENT_HEADER => 20,
 :TAPE_SEGMENT => 21,
 :DOLLAR => 22 }

racc_use_result_var = true

racc_nt_base = 23

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'COMMA',
'COLON',
'RPAR',
'RSQ',
'DASH',
'LPAR',
'LSQ',
'SESSION_HEADER',
'DATE',
'LOCATION',
'TRANSFERRER',
'ANYWORD',
'TAPE_TAG',
'WHITE_SPACE',
'PUNCTUATION',
'ID_TAG',
'EMPTY_LINE',
'EOL',
'TAPE_CONTENT_HEADER',
'TAPE_SEGMENT',
'DOLLAR',
'$start',
'tape_content',
'tape_content_header',
'empty_lines',
'tape_content_lines',
'tape_content_line',
'filled_line',
'tape_content_tag',
'word',
'punctuation']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'tcp.racc', 17
  def _reduce_1( val, _values, result )
 tape.content = content_buffer.flatten; result = tape
   result
  end
.,.,

 # reduce 2 omitted

 # reduce 3 omitted

 # reduce 4 omitted

module_eval <<'.,.,', 'tcp.racc', 27
  def _reduce_5( val, _values, result )
 val[0].description = val[1..3].join.sub(/\A /, ''); result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 28
  def _reduce_6( val, _values, result )
 val[0].description = val[1..3].join.sub(/\A /, ''); result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 29
  def _reduce_7( val, _values, result )
 val[0].description = val[1..3].join.sub(/\A /, ''); result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 30
  def _reduce_8( val, _values, result )
 val[0].description = val[1..3].join.sub(/\A /, ''); result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 33
  def _reduce_9( val, _values, result )
 content_buffer << TapeContent.new(val[1], val[1]); result = content_buffer.last
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 34
  def _reduce_10( val, _values, result )
 content_buffer << TapeContent.new(val[1], val[3]); result = content_buffer.last
   result
  end
.,.,

module_eval <<'.,.,', 'tcp.racc', 37
  def _reduce_11( val, _values, result )
 result = val[0..2].join
   result
  end
.,.,

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

 # reduce 21 omitted

 # reduce 22 omitted

 # reduce 23 omitted

 # reduce 24 omitted

 # reduce 25 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class ContentParser

  end   # module Tape

end   # module Tdp

#
# test code - to be commented out in production
#
#
# session = SessionDescription.new
# tcp = Tape::ContentParser.new(session, true)
# fh = File.open(ARGV[0], 'r')
# one_line = fh.gets
# session = tcp.parse(one_line)
# $stderr.puts("Session: #{session.inspect}")
